version: '3.8'
services:
  app:
    image: victorsouto/revisa-smart-api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://docker:docker@localhost:5432/revisa_smart?schema=public
    links:
      - database
  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=revisa_smart
  queue:
    image: 'redis'
    ports:
      - 6379:6379
